In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv(r"check.csv")
data.shape

(17635, 29)

In [4]:
data.head(60)

,iso_code,location,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,total_deaths_per_million,...,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cvd_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_100k
0,ABW,Aruba,2020-03-13,2,2,0,0,18.733,18.733,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
1,ABW,Aruba,2020-03-20,4,2,0,0,37.465,18.733,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
2,ABW,Aruba,2020-03-24,12,8,0,0,112.395,74.930,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
3,ABW,Aruba,2020-03-25,17,5,0,0,159.227,46.831,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
4,ABW,Aruba,2020-03-26,19,2,0,0,177.959,18.733,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
5,ABW,Aruba,2020-03-27,28,9,0,0,262.256,84.296,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
6,ABW,Aruba,2020-03-28,28,0,0,0,262.256,0.000,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
7,ABW,Aruba,2020-03-29,28,0,0,0,262.256,0.000,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
8,ABW,Aruba,2020-03-30,50,22,0,0,468.314,206.058,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
9,ABW,Aruba,2020-04-01,55,5,0,0,515.145,46.831,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
10,ABW,Aruba,2020-04-02,55,0,0,0,515.145,0.000,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
11,ABW,Aruba,2020-04-03,60,5,0,0,561.977,46.831,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
12,ABW,Aruba,2020-04-04,62,2,0,0,580.709,18.733,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
13,ABW,Aruba,2020-04-05,64,2,0,0,599.442,18.733,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
14,ABW,Aruba,2020-04-06,64,0,0,0,599.442,0.000,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
15,ABW,Aruba,2020-04-07,71,7,0,0,665.006,65.564,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
16,ABW,Aruba,2020-04-08,74,3,0,0,693.105,28.099,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
17,ABW,Aruba,2020-04-09,77,3,0,0,721.203,28.099,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
18,ABW,Aruba,2020-04-10,82,5,0,0,768.035,46.831,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
19,ABW,Aruba,2020-04-11,86,4,0,0,805.500,37.465,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
20,ABW,Aruba,2020-04-12,92,6,0,0,861.698,56.198,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
21,ABW,Aruba,2020-04-13,92,0,0,0,861.698,0.000,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
22,ABW,Aruba,2020-04-14,92,0,0,0,861.698,0.000,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
23,ABW,Aruba,2020-04-15,92,0,0,0,861.698,0.000,0.000,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
24,ABW,Aruba,2020-04-16,93,1,1,1,871.064,9.366,9.366,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
25,ABW,Aruba,2020-04-17,95,2,1,0,889.796,18.733,9.366,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
26,ABW,Aruba,2020-04-18,96,1,2,1,899.163,9.366,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
27,ABW,Aruba,2020-04-19,96,0,2,0,899.163,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
28,ABW,Aruba,2020-04-20,97,1,2,0,908.529,9.366,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
29,ABW,Aruba,2020-04-21,97,0,2,0,908.529,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
30,ABW,Aruba,2020-04-22,97,0,2,0,908.529,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
31,ABW,Aruba,2020-04-23,100,3,2,0,936.628,28.099,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
32,ABW,Aruba,2020-04-24,100,0,2,0,936.628,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
33,ABW,Aruba,2020-04-25,100,0,2,0,936.628,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
34,ABW,Aruba,2020-04-26,100,0,2,0,936.628,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
35,ABW,Aruba,2020-04-27,100,0,2,0,936.628,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
36,ABW,Aruba,2020-04-28,100,0,2,0,936.628,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
37,ABW,Aruba,2020-04-29,100,0,2,0,936.628,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
38,ABW,Aruba,2020-04-30,100,0,2,0,936.628,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
39,ABW,Aruba,2020-05-01,100,0,2,0,936.628,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
40,ABW,Aruba,2020-05-02,100,0,2,0,936.628,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
41,ABW,Aruba,2020-05-03,100,0,2,0,936.628,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
42,ABW,Aruba,2020-05-04,100,0,2,0,936.628,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
43,ABW,Aruba,2020-05-05,100,0,2,0,936.628,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
44,ABW,Aruba,2020-05-06,100,0,2,0,936.628,0.000,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
45,ABW,Aruba,2020-05-07,101,1,2,0,945.994,9.366,18.733,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
46,ABW,Aruba,2020-05-08,101,0,3,1,945.994,0.000,28.099,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
47,ABW,Aruba,2020-05-09,101,0,3,0,945.994,0.000,28.099,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
48,ABW,Aruba,2020-05-10,101,0,3,0,945.994,0.000,28.099,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
49,ABW,Aruba,2020-05-11,101,0,3,0,945.994,0.000,28.099,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
50,ABW,Aruba,2020-05-12,101,0,3,0,945.994,0.000,28.099,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
51,ABW,Aruba,2020-05-13,101,0,3,0,945.994,0.000,28.099,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
52,ABW,Aruba,2020-05-14,101,0,3,0,945.994,0.000,28.099,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
53,ABW,Aruba,2020-05-15,101,0,3,0,945.994,0.000,28.099,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
54,ABW,Aruba,2020-05-16,101,0,3,0,945.994,0.000,28.099,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
55,AFG,Afghanistan,2019-12-31,0,0,0,0,0.000,0.000,0.000,...,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5
56,AFG,Afghanistan,2020-01-01,0,0,0,0,0.000,0.000,0.000,...,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5
57,AFG,Afghanistan,2020-01-02,0,0,0,0,0.000,0.000,0.000,...,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5
58,AFG,Afghanistan,2020-01-03,0,0,0,0,0.000,0.000,0.000,...,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5
59,AFG,Afghanistan,2020-01-04,0,0,0,0,0.000,0.000,0.000,...,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5

In [5]:
temp = data.iloc[1577:1649,:]

In [9]:
temp.shape
temp.head(72)

,iso_code,location,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,total_deaths_per_million,...,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cvd_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_100k
1577,BGD,Bangladesh,2020-03-07,0,0,0,0,NaN,NaN,NaN,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.800
1578,BGD,Bangladesh,2020-03-08,0,0,0,0,NaN,NaN,NaN,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.800
1579,BGD,Bangladesh,2020-03-09,3,3,0,0,0.018,0.018,0.000,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.800
1580,BGD,Bangladesh,2020-03-10,0,0,0,0,NaN,NaN,NaN,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.800
1581,BGD,Bangladesh,2020-03-11,0,0,0,0,NaN,NaN,NaN,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1644,BGD,Bangladesh,2020-05-13,16660,969,250,11,101.160,5.884,1.518,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.800
1645,BGD,Bangladesh,2020-05-14,17822,1162,269,19,108.216,7.056,1.633,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.800
1646,BGD,Bangladesh,2020-05-15,18863,1041,283,14,114.537,6.321,1.718,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.800
1647,BGD,Bangladesh,2020-05-16,20065,1202,298,15,121.835,7.299,1.809,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.800
1648,BGR,Bulgaria,2020-03-08,2,2,0,0,0.288,0.288,0.000,...,20.801,13.272,18563.307,1.5,424.688,5.81,30.1,44.4,NaN,7.454

In [10]:
temp.to_csv(r"C:\Users\User\Downloads\BD_CVdata.csv", index = False)

In [11]:
temp.head(50)

,iso_code,location,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,total_deaths_per_million,...,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cvd_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_100k
1577,BGD,Bangladesh,2020-03-07,0,0,0,0,NaN,NaN,NaN,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1578,BGD,Bangladesh,2020-03-08,0,0,0,0,NaN,NaN,NaN,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1579,BGD,Bangladesh,2020-03-09,3,3,0,0,0.018,0.018,0.000,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1580,BGD,Bangladesh,2020-03-10,0,0,0,0,NaN,NaN,NaN,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1581,BGD,Bangladesh,2020-03-11,0,0,0,0,NaN,NaN,NaN,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1582,BGD,Bangladesh,2020-03-12,0,0,0,0,NaN,NaN,NaN,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1583,BGD,Bangladesh,2020-03-13,0,0,0,0,NaN,NaN,NaN,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1584,BGD,Bangladesh,2020-03-14,0,0,0,0,NaN,NaN,NaN,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1585,BGD,Bangladesh,2020-03-15,3,0,0,0,0.018,0.000,0.000,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1586,BGD,Bangladesh,2020-03-16,0,0,0,0,NaN,NaN,NaN,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1587,BGD,Bangladesh,2020-03-17,5,2,0,0,0.030,0.012,0.000,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1588,BGD,Bangladesh,2020-03-18,8,3,0,0,0.049,0.018,0.000,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1589,BGD,Bangladesh,2020-03-19,10,2,0,0,0.061,0.012,0.000,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1590,BGD,Bangladesh,2020-03-20,10,0,0,0,0.061,0.000,0.000,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1591,BGD,Bangladesh,2020-03-21,17,7,0,0,0.103,0.043,0.000,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1592,BGD,Bangladesh,2020-03-22,24,7,2,2,0.146,0.043,0.012,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1593,BGD,Bangladesh,2020-03-23,27,3,3,1,0.164,0.018,0.018,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1594,BGD,Bangladesh,2020-03-24,33,6,3,0,0.200,0.036,0.018,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1595,BGD,Bangladesh,2020-03-25,39,6,4,1,0.237,0.036,0.024,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1596,BGD,Bangladesh,2020-03-26,39,0,5,1,0.237,0.000,0.030,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1597,BGD,Bangladesh,2020-03-27,48,9,5,0,0.291,0.055,0.030,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1598,BGD,Bangladesh,2020-03-28,48,0,5,0,0.291,0.000,0.030,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1599,BGD,Bangladesh,2020-03-29,48,0,5,0,0.291,0.000,0.030,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1600,BGD,Bangladesh,2020-03-30,49,1,5,0,0.298,0.006,0.030,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1601,BGD,Bangladesh,2020-03-31,49,0,5,0,0.298,0.000,0.030,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1602,BGD,Bangladesh,2020-04-01,51,2,5,0,0.310,0.012,0.030,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1603,BGD,Bangladesh,2020-04-02,54,3,6,1,0.328,0.018,0.036,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1604,BGD,Bangladesh,2020-04-03,56,2,6,0,0.340,0.012,0.036,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1605,BGD,Bangladesh,2020-04-04,61,5,6,0,0.370,0.030,0.036,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1606,BGD,Bangladesh,2020-04-05,70,9,8,2,0.425,0.055,0.049,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1607,BGD,Bangladesh,2020-04-06,88,18,9,1,0.534,0.109,0.055,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1608,BGD,Bangladesh,2020-04-07,123,35,12,3,0.747,0.213,0.073,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1609,BGD,Bangladesh,2020-04-08,164,41,17,5,0.996,0.249,0.103,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1610,BGD,Bangladesh,2020-04-09,218,54,20,3,1.324,0.328,0.121,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1611,BGD,Bangladesh,2020-04-10,330,112,21,1,2.004,0.680,0.128,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1612,BGD,Bangladesh,2020-04-11,424,94,27,6,2.575,0.571,0.164,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1613,BGD,Bangladesh,2020-04-12,482,58,30,3,2.927,0.352,0.182,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1614,BGD,Bangladesh,2020-04-13,621,139,34,4,3.771,0.844,0.206,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1615,BGD,Bangladesh,2020-04-14,803,182,39,5,4.876,1.105,0.237,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1616,BGD,Bangladesh,2020-04-15,1012,209,46,7,6.145,1.269,0.279,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1617,BGD,Bangladesh,2020-04-16,1231,219,50,4,7.475,1.330,0.304,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1618,BGD,Bangladesh,2020-04-17,1572,341,60,10,9.545,2.071,0.364,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1619,BGD,Bangladesh,2020-04-18,1838,266,75,15,11.160,1.615,0.455,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1620,BGD,Bangladesh,2020-04-19,2144,306,84,9,13.018,1.858,0.510,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1621,BGD,Bangladesh,2020-04-20,2456,312,91,7,14.913,1.894,0.553,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1622,BGD,Bangladesh,2020-04-21,2948,492,101,10,17.900,2.987,0.613,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1623,BGD,Bangladesh,2020-04-22,3382,434,110,9,20.536,2.635,0.668,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1624,BGD,Bangladesh,2020-04-23,3772,390,120,10,22.904,2.368,0.729,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1625,BGD,Bangladesh,2020-04-24,4186,414,127,7,25.418,2.514,0.771,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8
1626,BGD,Bangladesh,2020-04-25,4689,503,131,4,28.472,3.054,0.795,...,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,34.808,0.8

In [27]:
temp.to_csv(r"C:\Users\User\Downloads\BD_data.csv", index = False)

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\User\\Downloads\\BD_data.csv'

In [20]:
data = pd.read_csv(r"C:\Users\User\Downloads\BD_data.csv")
data.shape

(67, 3)

In [21]:
data.head()

         date  total_cases  total_deaths
0  2020-03-07            0             0
1  2020-03-08            0             0
2  2020-03-09            3             0
3  2020-03-10            0             0
4  2020-03-11            0             0

In [25]:
header_names=['Date','Confirmed','Deaths']
data=pd.read_csv(r"C:\Users\User\Downloads\BD_data.csv",header=None,skiprows=1,names=header_names)

In [26]:
data.head()

         Date  Confirmed  Deaths
0  2020-03-07          0       0
1  2020-03-08          0       0
2  2020-03-09          3       0
3  2020-03-10          0       0
4  2020-03-11          0       0

In [32]:
data = pd.read_csv(r"C:\Users\User\Downloads\BD_data.csv")
data.shape

(67, 6)

In [33]:
data.head()

       Date  Confirmed  Recovered  Deaths  Number_of_daily_test  Total_Test
0  07-03-20        0.0        0.0     0.0                   3.0       108.0
1  08-03-20        0.0        0.0     0.0                   9.0       111.0
2  09-03-20        3.0        0.0     0.0                   7.0       120.0
3  10-03-20        0.0        0.0     0.0                  10.0       127.0
4  11-03-20        0.0        0.0     0.0                  10.0       137.0